services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/po_db
      SPRING_DATASOURCE_USERNAME: user2
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: po_db  # Замените на имя вашей БД
      POSTGRES_USER: user2  # Замените на имя пользователя
      POSTGRES_PASSWORD: pass  # Замените на пароль
    ports:
      - "5423:5432"  # Порт, на котором будет доступна БД